services:
  - type: web
    name: tv-tracking-app
    runtime: java
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 4569
    buildCommand: |
      apt-get update && apt-get install -y maven
      mvn clean package
    startCommand: java -jar target/tvtracking-1.0-SNAPSHOT.jar
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
